### ISSUE TITLE
Status Check

### ISSUE THREAD

**Issue by jchoi2022** [KAIST-IS521/2018s-onion-team5#10]
Hi, I am looking around the current development status.

I'm having a trouble in finding the "onion routing" feature in your repository. It seems 'relay' branch just implements a function that encrypts a given message with the recipient's public key. The concept of onion routing is somewhat different from this. Please correct me if I am missing something.

Thank you!

**Comment by omnibusor** [comment]
안녕하세요. 릴레이 브랜치를 담당하고 있는 양호준입니다.
릴레이 브랜치에서 현재 구현된 부분은 enc/dec함수만 구현되어 있습니다.
현재 소켓 프로그래밍을 통해 send/recv를 구현중에 있습니다.

**Comment by jchoi2022** [comment]
OK, thanks! I'll close this issue.

**Comment by jchoi2022** [comment]
Thank you for the hard efforts on the project. I have some questions for grading.
- It seems like the UI developed by S-KYUCHAN is not yet integrated to your product: for example, messenger_UI() does not seem to be called anywhere else than main() of  ui.cpp file. Is that right?
- In your presentation, the contribution slide states that omnibusor was responsible for implementing message relaying. However, currently generating onion-encrypted packet seems to be implemented in send_message() of main.cc file, and message relaying seems to be implemented in liste_loop() of listen.cc file: both codes seem to be completely written by AhnMo. Is that right?

**Comment by jchoi2022** [comment]
Thank you for the hard efforts on the project. I have some questions for grading.
- It seems like the UI developed by S-KYUCHAN is not yet integrated to your product: for example, messenger_UI() does not seem to be called anywhere else than main() of  ui.cpp file. Is that right?
- In your presentation, the contribution slide states that omnibusor was responsible for implementing message relaying. However, currently generating onion-encrypted packet seems to be implemented in send_message() of main.cc file, and message relaying seems to be implemented in liste_loop() of listen.cc file: both codes seem to be completely written by AhnMo. Is that right?

**Comment by omnibusor** [comment]
안녕하세요. 2번 질문에 답변드리겠습니다.

commit 2b0e2572958b5ac1cd0be1addd9e4606faf5f25a을 보시면, client/src/main.cpp 와 relay3.cpp가 있습니다. main.cpp는 S-KYUCHAN이 만든 UI고, relay3.cpp는 제가 만든 릴레이인데, 원래 계획은 main.cpp에 relay 쓰레드가 동작하도록 구현하는 것이었지만, 제대로 동작하지 않았습니다. relay3.cpp는 제가 구현하였습니다.

제대로 동작하지 않고 진도가 안나가서 AhnMo가 새로 프로그램을 만든 것입니다.

**Comment by S-KYUCHAN** [comment]
안녕하세요 1번 질문에 답변을 드리자면 messenger_UI에 node list가 필요하고 그  node list는 relay에서 받게 디자인 되어있어서  relay에서 node list를 받아서 주지 않는이상 UI가 불러올 이유가 없었습니다. 그렇기에 relay와 server의 연결하느데 집중했지만 해결하지 못해서 쓰이지 못했습니다.

**Comment by jchoi2022** [comment]
OK, I understand. Thank you for the response.
