### ISSUE TITLE
Checkpoint comment

### ISSUE THREAD

**Issue by sangkilc** [KAIST-IS521/2018s-onion-team5#11]
1. 각자의 브랜치에서 머지가 전혀 안되어있어서 프로토타입이 준비가 되지 않았음.
2. 좀 더 동작하는 프로토타입을 만드는데 집중하고, 기능을 추가하거나 완전히 하는 부분은 프로토타입이 나온 후에 진행하는 것이 바람직해 보입니다.
3. 마일스톤 역시 너무 피상적으로 짜여져있고, 세분화된 work 분배가 아쉽습니다.

**Comment by sangkilc** [comment]
또한 다음의 내용을 최종 발표때 보길 기대합니다:
- 제품 이름?
- 제품에 대한 기술적 특장점?
- 제품에 대한 멤버들의 열정

**Comment by AhnMo** [comment]
코멘트 감사합니다.
