### ISSUE TITLE
Offline meeting

### ISSUE THREAD

**Issue by S-KYUCHAN** [KAIST-IS521/2018s-onion-team5#2]
10pm at N26 2nd floor

**Comment by AhnMo** [comment]
# Shim
- Message Format class
- Message Crypto
- Command Parser

# Yang
- Thread Receive
- Packet relay

# Park
- Message Send/Recv
- PGP Fetch from Github server
- Health check (PONG)
- Server 
  - List management
  - Health Check (PING)
- Route path choice
