### ISSUE TITLE
Second meeting

### ISSUE THREAD

**Issue by S-KYUCHAN** [KAIST-IS521/2018s-onion-team5#4]
3/25 2:00 pm at N26 2nd floor
---------------------------------
- [x] Branch 각자 만들기
- [ ] 각자 맡은 부분 작업해오기
- [ ] 시간 남으면 다른 멤버 도와주기
- [ ] 1차 merge 후 conflict 해결
- [ ] 더 필요한 부분 생각해보기

**Comment by S-KYUCHAN** [comment]
- [ ] 1차 merge 후 conflict 해결
- [ ] 더 필요한 부분 생각해보기

**Comment by AhnMo** [comment]
Schedule delayed.
