### ISSUE TITLE
To do list before next meeting

### ISSUE THREAD

**Issue by AhnMo** [KAIST-IS521/2018s-onion-team5#6]
- [x] Message Send/Recv
- [x] PGP Fetch from Github server
- [x] Health check (PONG)
- [x] Server
  - [x] List management
  - [x] Health Check (PING)
- [x] Route path choice

**Comment by AhnMo** [comment]
# Server Considerations
- Node list, how to prevent race condition?
  - save as a file, it can handle by os to prevent race condition.
  - If health check with c-r method, token must offer. 
- Listen broadcast the client join request
  - After receive broadcast, make connection with client as TCP. And send the list of data.
- Health check.
  - just use ping implementation or challenge-response method.
  - If we use challenge-response method, how to communicate with client, TCP or UDP or other?
    - If UDP, client must have listening routine with UDP... 
    - If TCP, isn't it quite big overload?? 
- route path choice

**Comment by omnibusor** [comment]
pgp_enc()
pgp_dec() 함수 구현완료.

짧은 문자열/짧은 문자열 파일에 대해서는 제대로 작동. 하지만 매우 긴 문자열/파일, 바이너리 파일에 대해서는 작동하지 않음. 바이너리 파일은 모든 plain data를 문자열로 받아서 그런것같고, 매우 긴 문자열/파일의 경우 popen했을때 file read를 전혀 하지 못함.

따라서, plain data를 모두 문자열로 받을 것이 아니라, 짧은 문자열의 경우에만 char *로 받고 나머지는 file로 받아야 할 것 같음. 이렇게 하려면 함수의 파라미터 값을 바꿔줘야함.

pgp_enc()를 호출할때, 파일을 읽은 후 읽은 데이터를 인자로 넘겨주는것이 아니라, 파일포인터 자체를 넘겨주는 방법이 적당할 듯 싶음.
