### ISSUE TITLE
PGP ENC/DEC 및 릴레이 쓰레딩 구현

### ISSUE THREAD

**Issue by omnibusor** [KAIST-IS521/2018s-onion-team5#8]
TODO
----------------------------------------------
1. PGP ENC/DEC 구현
 1-1. PGP ENC 테스팅 프로그램 구현
 1-2. PGP DEC 테스팅 프로그램 구현
 1-3. PGP ENC/DEC 테스팅 프로그램 구현
2. 릴레이 쓰레딩 구현
----------------------------------------------

고려할 점들
----------------------------------------------
1. PGP ENC/DEC가 입력 문자열을 받을 때, 문자열에 \0, \n, ", 등과 같은 캐릭터를 어떻게 처리할 것인가?
 -> 모두 문자 그대로로 처리함.
2. PGP ENC/DEC는 gpg 프로그램을 호출해서 사용한다. 커맨드 인젝션 공격에 대비했는가?
 ->인자에 ""를 붙여서 커맨드로 인식하지 않도록 함.
----------------------------------------------

1. pgp_enc()
pgp_dec() 함수 구현완료.
짧은 문자열/짧은 문자열 파일에 대해서는 제대로 작동. 하지만 매우 긴 문자열/파일, 바이너리 파일에 대해서는 작동하지 않음. 바이너리 파일은 모든 plain data를 문자열로 받아서 그런것같고, 매우 긴 문자열/파일의 경우 popen했을때 file read를 전혀 하지 못함.

지금 pgp_enc는 모든 plain을 문자열로 받게 되어있는데, plain data를 모두 문자열로 받을 것이 아니라, 짧은 문자열의 경우에만 char *로 받고 나머지는 file로 받아야 할 것 같음. 이렇게 하려면 함수의 파라미터 값을 바꿔줘야함.

 pgp_enc()를 호출할때, 파일을 읽은 후 읽은 데이터를 인자로 넘겨주는것이 아니라, 파일포인터 자체를 넘겨주는 방법이 적당할 듯 싶음.

1-1. PGP ENC 테스팅 프로그램 구현 완료.
1-2. 아직 구현 X
1-3. 아직 구현 X

2. 아직 구현 X

**Comment by AhnMo** [comment]
짧은 문자열에 대해서 정상적으로 동작하되 큰 문자열에 대해서 수행을 못한다는건 읽어오는 것에 문제가 있다던가 버퍼의 크기가 충분하지 않다 라고 생각이 되는데 아마 고정된 크기로 한번만 읽어오는게 문제로 보입니다.
```cpp
cnt = fread(*ciphered, sizeof(char), 1024*1024*1024, file);
```
일단 버퍼 크기 생각 안하고 작성할 수 있기 위해서 저라면 이렇게 작성하지 않았을까 싶네요.
```cpp
std::string buffer;
int f_size = get_file_size(fp);
int read_size = 0;
while (read_size < f_size) {
  char temp[BUFSIZ + 1]; // BUFSIZ is defined in stdio.h
  int cnt;

  cnt = fread(temp, sizeof(char), BUFSIZ, fp);
  temp[cnt] = 0;

  buffer += temp;
  read_size += cnt;
}

if (f_size != buffer.size()) { 
  // something is wrong
}
```

**Comment by AhnMo** [comment]
파일 포인터로 넘긴다는 건 이렇게 생각해볼 수 있겠네요.
1. 파일을 메모리로 읽어온다. // Memory Bomb 1
2. 파일내용을 포함한 command 문자열을 만든다. // Memory Bomb 2
3. 해당 명령어를 실행한다.

pgpme와 같은 라이브러리 함수를 쓰지 않는한 굳이 읽어올 필요가 없다고 생각이 되구요.
구조를 이렇게 가져가는게 어떠신가요?
```cpp
// string a;
// a.c_str() == const char *;
// &a[0] == char *;
// a.size() == strlen(a);
bool pgp_enc_file(string filename, string recipient, string& encrypted) {
  // gpg 명령어 만들때 stdin을 읽어와서 암호화 하는게 아닌 파일 명으로 해서...
}
bool pgp_enc(string plain, string recipient, string& encrypted) {
  // 파일로 plain을 저장
  return pgp_enc_file(filename, recipient, encrypted);
}
```

**Comment by AhnMo** [comment]
그리고 이전에 command injection와 관련해서 말씀드린적이 있는데 혹시 어디가 예방책인지 알 수 있을까요??

**Comment by AhnMo** [comment]
그리고 `common.c`에서 파일포인터에서 파일사이즈를 구해오는게 있는데, FILE 포인터로 열어서 하지 말고 `stat`함수를 이용하는 것이 어떨까요?
https://stackoverflow.com/questions/5793030/how-to-get-file-size-on-disk-on-linux

**Comment by omnibusor** [comment]
피드백 감사합니다.
1.
```cpp
cnt = fread(*ciphered, sizeof(char), 1024*1024*1024, file);
```
1-1.이 부분같은 경우는 한번 해보겠습니다. 
1-2.그리고 popen으로 file을 오픈해서 생성된 FILE 구조체로는 fseek()을 사용할수가 없어서 파일 크기를 구하지 못했습니다. 실제로 get_file_size()를 사용하면 fseek에서 에러가 발생하더군요.
https://stackoverflow.com/questions/19187131/how-to-fseek-on-a-pipe?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
2. 파일 포인터를 넘기는다는 말은
```cpp
FILE fp = fopen("file path","rb);
```
/*
fp 자체를 넘겨주는걸 고려하고 있습니다. 일단 메신저를 실행하고 터미널에서 파일을 넘겨주게 되면, 프로그램은 파일을 fopen만 하고 fread는 하지 않습니다. 그리고 pgp_enc()로 FILE 구조체의 주소(&fp)를 넘겨주어서 pgp_enc()에서 file read를 하려고 합니다.
*/
제시한 방법이 괜찮은 것같습니다. 어차피 메신저에서 파일을 보내기 위해서는 먼저 파일이 존재해야 할것이고, 이를 굳이 fopen으로 열필요 없이 파일 주소만 패스해주고 gpg가 이를 처리하도록하는 것이 가장 좋아보입니다.


3. stat함수와 file pointer를 여는것의 성능차이가 있는건가요?

**Comment by AhnMo** [comment]
1-2. `popen` 말고 `system`을 사용하시거나 `fork` 후에 `exec*`계열 함수를 통해서 해볼 수 있을 것 같습니다.
굳이 `stdin`, `stdout`를 가져다 쓸 필요가 없어 보이기 때문이죠. 
(A) 문자열을 파일로 저장을 하고, (B) 암호화를 수행해서 (C) 암호화된 파일 내용을 가져온다면, 
(C') 암호화된 파일 내용을 가져와서 (B') 복호화를 수행한 다음 (A') 파일로부터 문자열을 읽어와서 출력을 하면 되겠네요.
물론 더 나은 방법이다라고생각 하시는 걸로 진행하시면 될 것 같습니다.

3. 제가 경험했던 것에서 `'\0\0'`가 말썽을 많이 부리고, `lseek`를 통한 파일포인터 이동 또한 말썽을 부렸던 것으로 기억합니다. 그리고 함수 원형을 보게 되면 `fopen`으로 굳이 열어줄 필요가 없겠네요. 
```cpp
// https://www.joinc.co.kr/w/man/2/stat
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

int stat(const char *file_name, struct stat *buf);
int fstat(int filedes, struct stat *buf);
int lstat(const char *file_name, struct stat *buf);
```

**Comment by omnibusor** [comment]
결론
--------------------
encryption할 때, 짧은 메세지는 파일로 만들지 말자 vs 상관없이 전부 파일로 만들자.
1. 짧은 메세지도 파일로 만들 경우, fopen, fwrite로 인한 성능 하락 우려.
2. 성능 하락은 존재할 수 있지만, 파일로 만들지 않을 경우 파일 사이즈를 알 수 없기 때문에 fread()에서 버그발생 가능성 우려.
합의: 버그 차단이 우선. 2안 채택
-------------------
